import java.util.*;

class FirstUnique {
    public static int firstUniqCharNaive(String s){
        int[] occurences = new int[s.length()];
        for (int i = 0; i < s.length(); i++) {
            occurences[i] = 1;
            for (int ii = 0; ii < s.length(); ii++) {
                if (s.charAt(i) == s.charAt(ii)&&ii!=i) {
                    occurences[i]++;

                }
            }
        }

        for (int i = 0; i < occurences.length; i++) {
            if(occurences[i]==1){
                return i;
            }
        }
        return -1;
    }

    public static int firstUniqCharOptimized(String s) {
        Map<Character, Integer> map = new HashMap<>();
        char[] sChar = s.toCharArray();
        for (char c: sChar) {
            if(map.get(c)==null){
                map.put(c, 1);
            }else{
                map.put(c,map.get(c)+1);
            }

        }
        for(int i=0;i<sChar.length;i++){
            if(map.get(sChar[i])==1){
                return i;
            }
        }
        return -1;
    }

    public static int firstUniqCharMine(String s){
        char[] sChar = s.toCharArray();
        Map<Character, Integer> map = new HashMap<>();
        for (char c: sChar) {
            if(map.get(c)==null){
                map.put(c, 1);
            }else{
                map.put(c,map.get(c)+1);
            }

        }
        for(int i=0;i<sChar.length;i++){
            if(map.get(sChar[i])==1){
                return i;
            }
        }
        Map.Entry<Character, Integer> thing = map
                .entrySet()
                .stream().min(Map.Entry.comparingByValue(Comparator.naturalOrder()))
                .get();
        return -1;
    }

    public static void main(String[] args) {
        // this are long strings that you can use to test the efficiency of your code
        String longString1 = Consts.LONG_STR1;
        String longString2 = Consts.LONG_STR2;

        // code to test and time your solutions
        long startTime = System.nanoTime();
        int res = firstUniqCharNaive(longString1);
        long endTime = System.nanoTime();
        double duration = (endTime - startTime) / 1000000.0;
        System.out.println("Naive Result: " + res + " Time Taken: " + duration + "ms");

        startTime = System.nanoTime();
        res = firstUniqCharOptimized(longString1);
        endTime = System.nanoTime();
        duration = (endTime - startTime) / 1000000.0;
        System.out.println("Optimized Result: " + res + " Time Taken: " + duration + "ms");

        startTime = System.nanoTime();
        res = firstUniqCharMine(longString1);
        endTime = System.nanoTime();
        duration = (endTime - startTime) / 1000000.0;
        System.out.println("My Result: " + res + " Time Taken: " + duration + "ms");
    }

}
final class Consts {
    public static final String LONG_STR1 = "fsbnsfpiwgcvwvjxqixfhdgulgscdlcyaigckuvbgdbmudquwiffhiomqdxxageqlvesbagfbisalafrcfivalljeydskenpojdsosihsmqcbrdforhnbsrricttnfumpywisoquxtouyuvdvmwjrkktghiajljkjdddiseylhviaykvlhbsahpgyfcjdtqkupgmnwxslghgipwwwydqisexufiheujiatygtcqqpgqermisllnvfbtlxkqextfsqxrbhglcgbivrhqacxmkrikjokqsbyxviuwyuebfsftwperekdsudabrgaowxbdjxoqxrpufpshkqmbnehasttavdsovapjhxodaqtjtwwpqtjdnwwdeicisiovwfjcjhxkwwjncfnkkkgfeapqokvjfshlgufnwisghjtxgkqmxajnqpsdapqjsnceklfxobngsickgbodjuavdvtdakhsqnvjpgxhfjbfejaagkdyiphepbnfcuflvuacqnsihlyhoxfpwygxrhwjghswwsranepvapejjnfgycwgpdpmjlljspbiatswpkdluouvinpmrrksatglvjxnnvugrupjhjedotfhurrbbmryaprirfjulqrtlqkxmkshsxowhaeoxcuiqxoiwesomjxsdojtpxrwffigimwnnhhimnyeodfaehlrhopwillweteosvqbhcdlgdnpkukdvwriwqkjdepussfkihgmelmobdcbtycigpalcsntcqevypjnebgwbxkiaealjlijppflagymuugnnjbvxlofuheknkwpmpjuhixoacetidmpgcaidlqdqvpmgmluofnvfannobbexsbpsfhdmtlrcqccrasvbyfmmgwvbenpvsevgxammcoltgcidpmafqdbqkbydnpjttkpfftjwbqkqlruhnwxhskmaaeuwtytebnwiksmedmnmufbfjmppwvhenlhyrmpkgwbhccvbkmpgljniheaaemlwejbrkhklisdtwpouglpnhqgbjspbmfflfsmarcmxkgethnsavcmkoomhucyssfrbpurtgmjatcxacemxabdxynhaydgupofbddmqjcjpnbupgitpbylheqtwrwldbuxoaptwyfpokitpuynkoakiahgvakiuhhqagyeualygaollqqvfbohaphiismonyiikstqwjaonewjrgfdogsggnwpqfrxkuiyakuuubkbyhkxlwkktnfqhictsujqacoxwxiwmvdmootxkofwlfpedqykpelvpgeslttfidocrbdcdpwnxjsmtjeluekwfsftwpnqqtvusomvokktpxvmdjwecnropmylauxchuccxhxxdatgjstfbxngdwljurwccsdqlvrtatffloxukjxrwndrvpphsiopwfnuaeljvcbvlimkybjefngbtxlbpglmcvbaxaluumqdrjdcdxrvqahhouciagkisviptjlwqiaxhboxugjbqwimsgwqxednwxivdhgxkqismeyomqxycchqnanyxjkbgwgysisdxvbiioxdhlgxenllvqcvsdvsmdqxfnsmbulkwebhejtnokxjqyrjyyfudhmpfwpyelkyxwjsegoobccmacatoialyxdgbjsugiplsbmwlgtfhplbvncaldbhljjdempiuubqbjcnktlexbbdkrmhqqdlqduioprrpjtkirqyhboswpokkcguhuegovoecuckajcphrdjoaevthvbsblannugcitvodmileotiqlcdvblymvascgtqgcusnplgfckypqpwpjurgglacrpovlruxeljbnguihdhhqvbeouqrteimcdqadyspcthhmxernxrfivlhckysvmmqcktahsocdwonskgcwihrwrcroxipasyeonruflfcyoqlysjhntgmpmwkummknhnyqeiqkcbhmuplbjkgeiqdajrcxhvyexbpnnnekvnhyudiknbnycamdyprmaiufbhysepfqqorvoqpxjqdnnsxgqhpfoqjokblcybopvdqrfrxnbefrgtegwhqoxckjjyirrajdyycxextrgfdhwgolpyodsgssqewwrxojdqyrtontmulpiqsvirdpcqyemmtuissciwjrbrtcuktdtvabycnoyikinkpxqbdaufcgdxoproaxgikvfwmaurshvpvkatuwndwbsowxhwrmvkckgxsanplkvgnevvwicylmvtkmyykbvkkvffwlvmgdgrgachckenoikrjymxucjqhfaejsucvqtstkwlnerlaxinpkxbwoeacbpkiskobdnbuosruulfcxafhnfeswpahuuityywtrrqhcqqtnrcocukaointguhahhmyedxwkfgigpgxguxjiiiyvwwlgbaqdotejvnkeriwpwxjumeaplfouafyhtdanhxvffrahgqpyxlinirdtwljrwdmdtlqevgrwinjdacxmetpndpcgxtfngfrwxkadrqgevisjpxgmowcgcyoujnlaukjctxhxtrpbllkitbjltuppllamxtvybsxprbtmihgokabgaodprkkssvcmwncqvpveskuwhpqxaipyhlijautjqfhwltcwdtxxbrsiexwochybnbapvdkwqgixarivymtwttgkdnfwmxgyvcjadaiofiogjeexvljdoswokxsquotoqdkfwtmtyxbcoqkeljjwlkqqovmcooulbkqjqwnjibjlshgbehxvvahkuvavyqsocxrdthuopajesajowbgrjwiuexpdafpylcnuhcsaeofnhmkgmqtldmolxqrhwnjftourceitgpehkevbtxpqdgbljrslcnstcwmqqlpbpmaljhqftxqyxarwqcgixnsupjnqrioprpynpiakqahnyukisslieplniqbbtmhhmfijkjrhjcrksyuppnelfjutwymlkwbkypqpwpjurgglacrpovlruxeljbnguihdhhqvbeouqrteimcdqadyspcthhmxernxrfivlhckysvmmqcktahsocdwonskgcwihrwrcroxipasyeonruflfcyoqlysjhntgmpmwkummknhnyqeiqkcbhmuplbjkgeiqdajrcxhvyexbpnnnekvnhyudiknbnycamdyprmaiufbhysepfqqorvoqpxjqdnnsxgqhpfoqjokblcybopvdqrfrxnbefrgtegwhqoxckjjyirrajdyycxextrgfdhwgolpyodsgssqewwrxojdqyrtontmulpiqsvirdpcqyemmtuissciwjrbrtcuktdtvabycnoyikinkpxqbdaufcgdxoproaxgikvfwmaurshvpvkatuwndwbsowxhwrmvkckgxsanplkvgnevvwicylmvtkmyykbvkkvffwlvmgdgrgachckenoikrjymxucjqhfaejsucvqtstkwlnerlaxinpkxbwoeacbpkiskobdnbuosruulfcxafhnfeswpahuuityywtrrqhcqqtnrcocukaointguhahhmyedxwkfgigpgxguxjiiiyvwwlgbaqdotejvnkeriwpwxjumeaplfouafyhtdanhxvffrahgqpyxlinirdtwljrwdmdtlqevgrwinjdacxmetpndpcgxtfngfrwxkadrqgevisjpxgmowcgcyoujnlaukjctxhxtrpbllkitbjltuppllamxtvybsxprbtmihgokabgaodprkkssvcmwncqvpveskuwhpqxaipyhlijautjqfhwltcwdtxxbrsiexwochybnbapvdkwqgixarivymtwttgkdnfwmxgyvcjadaiofiogjeexvljdoswokxsquotoqdkfwtmtyxbcoqkeljjwlkqqovmcooulbkqjqwnjibjlshgbehxvvahkuvavyqsocxrdthuopajesajowbgrjwiuexpdafpylcnuhcsaeofnhmkgmqztldmolxqrhwnjftourceitgpehkevbtxpqdgbljrslcnstcwmqqlpbpmaljhqftxqyxarwqcgixnsupjnqrioprpynpiakqahnyukisslieplniqbbtmhhmfijkjrhjcrksyuppnelfjutwymlkwbfsbnsfpiwgcvwvjxqixfhdgulgscdlcyaigckuvbgdbmudquwiffhiomqdxxageqlvesbagfbisalafrcfivalljeydskenpojdsosihsmqcbrdforhnbsrricttnfumpywisoquxtouyuvdvmwjrkktghiajljkjdddiseylhviaykvlhbsahpgyfcjdtqkupgmnwxslghgipwwwydqisexufiheujiatygtcqqpgqermisllnvfbtlxkqextfsqxrbhglcgbivrhqacxmkrikjokqsbyxviuwyuebfsftwperekdsudabrgaowxbdjxoqxrpufpshkqmbnehasttavdsovapjhxodaqtjtwwpqtjdnwwdeicisiovwfjcjhxkwwjncfnkkkgfeapqokvjfshlgufnwisghjtxgkqmxajnqpsdapqjsnceklfxobngsickgbodjuavdvtdakhsqnvjpgxhfjbfejaagkdyiphepbnfcuflvuacqnsihlyhoxfpwygxrhwjghswwsranepvapejjnfgycwgpdpmjlljspbiatswpkdluouvinpmrrksatglvjxnnvugrupjhjedotfhurrbbmryaprirfjulqrtlqkxmkshsxowhaeoxcuiqxoiwesomjxsdojtpxrwffigimwnnhhimnyeodfaehlrhopwillweteosvqbhcdlgdnpkukdvwriwqkjdepussfkihgmelmobdcbtycigpalcsntcqevypjnebgwbxkiaealjlijppflagymuugnnjbvxlofuheknkwpmpjuhixoacetidmpgcaidlqdqvpmgmluofnvfannobbexsbpsfhdmtlrcqccrasvbyfmmgwvbenpvsevgxammcoltgcidpmafqdbqkbydnpjttkpfftjwbqkqlruhnwxhskmaaeuwtytebnwiksmedmnmufbfjmppwvhenlhyrmpkgwbhccvbkmpgljniheaaemlwejbrkhklisdtwpouglpnhqgbjspbmfflfsmarcmxkgethnsavcmkoomhucyssfrbpurtgmjatcxacemxabdxynh";

    public static final String LONG_STR2 =  "cqxrjvdxsngqmthvdnvixlstgxanmewrtpfqqevkaglltxmclnjhtifjgtuimrgftpkcerebevakdkmgruvxoclbxsbksadsaplpxnofuvtdacuqdhsrwtqksbbrsjitbguhgalnlawufsmxovwebovumwjjbtevjfhqvujbdkxopwiixqtodtnltlffkqvsqrtatpnqpjpmqeljgtgtnlvprnmtjpuwwvopmbfblrkbvucfxowaiuwdrtvhilschebfnklvufwlcltppddvodedxliifrrmmkssboigjrrettebslkaagckvmkaeimtfbgchmudrapperibsgcxumsdvlsolhjxxtkioodsgpafeiecoeituuaribfiegcuhihxcewdgkitvqdenfuruwfsjalnhnowgujwcsibecnulwujqqfvlfqeassgxenduotrmxqqpabahffprwdrrewvieolkenelcjevnatdsmxjjoovhmxaaokkiiofimwbdlrtscmdrujshhkufeafjtsvwkoegbhleumbliguaejduqkesdfaauwvilbejbiceiqvtqwhmoxbhotnxnfaaaluteajbuvjcmadorcvhbkjwxusiqnqvokupsvrlaatoqhbfssehlsncuwvmkjbxedassjjcidcfxhopmsochsodjcxkcvhbcpugbpokoheeucjbtdqxsnsigusfrbbxvidqjcvvwvibvcacwfevmphuunewqpmaatgdoasqenuicdbnhvkiuqqopptovxvipgabrcnfhrjcgxisbhxgcgsrxdtchpepmpdmbqnstlvxvdwtnfqiniotfxtbqvociuexpbqvhirgkhoxcenpfuarhfwswuaihqagpsanbkxvsnshxumdvcithhliqlrmildpuikhlckmccoqtilqqurdjkilulxdlxxsmxltputujuqapujpqlbvuqpwasbejcqsaknfthbfrnvbnnltglawrndjsbnvnamagviisplkrrktbxfasmdpmaitxmommqnhqknxapdseqpsrotgnvkifsfhjhjiipunlihbdwnfaeinrnmbamilkmloxnxbjitpqglkaulmsrxxdwucatnsdvcabkvqrvhfsjjslxohxxgwcsmxksmlncxwkrppuuccqwhenugollnbnxifuposbfmhdvlnctmeivxuxlbskucggbwxltnjaxqfklmbsudsvbxswarlpddqsowvrvxewdjqkssmvjwjgonlbgefbbfckelabjjppcnucmapdippkxevmdevmmofhebvpqauigufqvwhqwvdpolcpplgmxqajucfqamcgwoxuqeqhmflwkpqhdgxaqinoumfjdmapbshkovxovfdwjopmceonhusdrwikajmpdshnidhaciacvditdremjomuuavspwehoqipqcrggbnnrogxeamlelacjjpoihfunofbwonbvosuswvdfwuwqbjbcqbhpdxjhidcvkivjnravnbrwhdcgvtwcnhldumrbbkwscpqmgqqsfecgoaiscrpglajuicjbeodgxbduhruvnxdclmpjmfdiexiujhmvdjlrmwnfnwountnackfdtqalbjmxfwfhrfxrvedmpewedkfablbcjprqllqfjbftqntuxtvdshowmangolllpjtnbanjijoaekmxdrnsdgercanojxiwujarsiwqwvsgnxmweduvngwodasiasbumbjcrnsqsghxlfaachghagdtriuehmddlxpuocxiewfkmrfmtabxikgrwsfohgixphkeovppcdsfvmvilgjfuovrhfwadwuwmghfsafwalagngqltarnfmjvvwnpguncechqeofedubsqcqhxhcatmnuaphjjtrrgfnfodcxalpaswipwoacxfaraqlqlkgikdbsbgtkbubwkcreewvfnmxdcxfgitkpbtcdwxcnsjfneslmkkqvukhaprnsohinasijlbmkpjroujtuqvhcnnuomcbrgcsbktbbierrthmiaxircxhcetlujmwskrtusmbnlaqqpfkvewctxbgptwomocsaauipbtkfntivjxeftuaexeuepktrjtpnddjqoqttigiuvjciulmkajvvuxamfavfepwsucruwbndsjqamalrubuicpdmtqhvujqkwfxfdcpgxmfvopkwlxcojhbrkffsblmqtflochagrnimewgdqigxoutmsvjfgainjgtalghstltlqpcbiaepsmlamntshcksfpakijtsscoolgukwocevsqdnmvotquhwuolfoqepgimlckcdjdmxcjsexhmafdmmrkjkvdvwioiorbfsgpxtpspmfhlfxngsdjkpksficwskcadekegaqciwexnimdwwegrkmshjjwbdvfwhcdmuqkefrgfawaxsldnrkhfnomroqhgdsufkskakvuppotkmcrakospdavqhuasokegcpmbhnqmpjprvfuxrceefmqmpwqwgsaplsqxapwjfgwlhogmcnnkcthucfxkmwwmmtmpqncdkvbiownpwigwgoscjdhcliwdijudaokiplhcoxhbrefaefgvclbdqpgupcsosltvohixffkwdpttxcxuqiueiaohacamssbklxkwsrhwlxtcdkxmgvggmrugmofsqkbepjvmwtehgieakntavpdrstuamenlnqpenuptnngnuqrkwfhgqsceixoqnkgawpxqwestunessdjcpijchmrbnsrnuglwpirwdpirwdjtohckkbwpepaimksekvjqpdbvrmvflgvrqpxievvqtjgmhvcegaxkllndvneshwbaqqqanjooxegtfemtklwumswskeahbofcstxggjsissaaemawgbpgiaqxvjjtplgjjcnkuktnjsafahuibhtafcarsxldhxxsevkhiiimpjrvjgegcqhbmjdddkumhrkpgwbheenpbljefkeupkwuxtdtodnqcstrifgrubfkntijcsetljvvcbwgxmdcmdestkrbvthgohmbhkdxemucxhxeahpxooneaqbidelfiljkaachvjasnkcdaqxfkkqxgadxtlsjaaawthtvnbdbjhlmhuseninwvqvfcljjfjwjpgvdwxbxmxxrrntrtpnlblxnqfdiudfmuafhkhvefahekbxjffemiivrpblongpcnxdrikdbgpjcnnxjkebohegsqqnpchafdjfthcvwgwbatbvsvvlemxmlipkvqtolrfhxtgkvvxgpxujdkpaqxiihkpdgtwoiwhsubpleaorlvqohvmhoacibmohkawfotpowfmheormjqopogvwmxfbpihdhgcrrbcmnvvvxepqejxwhjdssvkxfxbtedqriacmxmctgaoumvjssbqpomqkaqapdeqeiuwpoqnjwwgcobwdfbpovbuxljldnbjmmuajfgpkwaticnvempiipvuqhuoiupdcexkxlcjfqhltxrakgfqxcudokhivqfxqppeoltlttdcbfqntptghrusfsnkhbqimqfogunamlaocroewjsdctvduxbqunvvojdwtcgdnvdphqikpdncgwvwbsqnlbqrromoahrlnesjldktkdttkkxkvfddhuvgkltvrilvumcwnwavngdgndbddgxbeldnirmcstpamjuijaguhfvijpfgprretxptfwiuxbmhkdmrdewhhexefwkkfdqvieuxjltsbcnmcriskcvvkwmfacoulxgtfvwuujvpbrilqmkhalrenrdjhomcnkvasqttiliitwjkudkstlaspsdqlsvlualjadooltdkslbibdcvjcxxaakwrqfljvnimbegcjbtbojlulmajghxaghmvkertseokewlvdhwljmusmbflqfcuecxcoxlqfeeswwrblkkjntfrurlllakohxpwkiodtfjkgblvlabmsqushilndnpuwbgqexalhdajpiuiqcoelhvbdlqdjdnqksjnnqwbmblnslndvsofmflkmbghuwknbtnqmooitxqkvhgagtorxtmoofajjabuwfjkeibuftnqfsljsaaixjwlxejiotodgvpotnuigcgfqvwfiodvmhlfswflcrkifodpgkxfbhkicjecxsctcqjhmhdlshfrlxmmrperrwcxsxgjckrntmvfigcuefmsjtgwwlrnktmjsdjwtuiovgptqlakkvaovjjkpefcmvgbanwwuhpcrdudmrqbitshpbcmopuksouukvrwchxvasvrulmoodgosuuurkiwgqqhatlwjoiowkivdxirjrawgqamkglsaxtmmwjkaskbqcwsbfnptfjhdgtibrglrfiwjkdodpocxxmgkvqskrifhjuubqefjotorgrrtkktusnieatdskptbnscvgjoqlpwbmfmhwkofmsncqpleqrubkrvxfjoobgqsdjcqwtaoaaojviojvrouaxgncwewpsxverwqdolaxwohbhbdqqgithxmolcnbfseawelbdufiuqeqvjjnxtjxwjmnaaixonjwtvsgmgcgdkuxdlcgmfstanlhqcdgfehvhqnhwjenrffurppswreunoecfrritjlfsmbcwdddiuwwkvjsajorbfukfistltmqjgusqppajruomckkbuwolkamdlidujxbqluhmsbarvcggjnjfuldnfqhsuejigepksqsjohjebejqoddnbglegvwhdbouwuhjpkbpjieolkhewxsaigvnlvepomgrwtwjwsclbfqgkkpiqadnuktgwftkvrioqigoateucpbbflshiujmoweqwqekscebetxtxotqrhpdrejcacikufakgmfccwkbxgwbjhithwofsxobnncvqauehonchgnpcdxqwvwhiosffrtmowoitfuawtsfrcqumhkjvmoekplblunpfvxcaliuralpglwjqjilaiivutatissdtbuckjpqimqfdxqswonjskckanaamgjroijaiwtcgwwfgjqlprpjkihacjoldlwxkojggavwulomhqdbpxxcpjsalegjdwfnemrmaeuerrchnufhxbnoutfgnedehbejaqppldgqhbbccemvrqkpfmqkkwrpgpsxdwkqahkrputaaqcuafukmetdvwvuhrckkfbepihcudoicslpwqheaxmbjhvqugljpbaxuncmqwahsmiobmshprxbxiadodflhaxfgmgiprwnjbxtrrnvoxeljosixkjwdbnkpualvgnvdedktdjrjlaumouamhmfqrhqplvknuogmbskjxlohuqnvdvhrhnpebtjoafvfrjjjbxcrxdmkpucsbisfxkuleudrncqwnfflktjcchesvtkwqtrnmbprwbfvgruvukawrurrxpfcxahmpccsgrrhhtmcjaifdhlcatmqdgokecllhgoqigdewellorpidafrhldupcwocdjokwgkobvphqxkvfobejixopegvswxshwouitltbajtlqvhjtpovhbntdiwnjruqnninorhdmbvjcrknexhnthgbsxrfkaxsprknbgvlxjjphpctgnxpltplwwfdrskeargmvvtewirksuficuuunwpbvkahvvfhokrubjbannccdukkifrllhcorjiodmttonkrogiinpwoiqbnnaaixvaemvnmuiekaskvddurgkjcxsqdxgkjekwrpkopmhaftocpenvttufbgdkvbdbbptmfwqkxfrgspipgohockiktekukiaaqufxioatwlixecrjntwcuiwehpqevrxoolnerbujwtlgaeogqekerdbiptgxwsqnqlxntxcxqekjicompnmevkunddjvbuxgekcbxvbgdlddnncqwdpmaqupjoqaapvfxsprunwqsndkhpquppdkqrdvhuljckardpnoxqnlceiswcjrlsdsirphllncseaeeauukamjnrmvimlgptiughdpdndqoariaggeqwjpjelwxxoaxrnsupkqscaodetdjuorpniqfedxgsfgebeddbxncddxpfmwuirxjennudsjpcbcodlglhjubibdrucvwhqsxqxctqfbwrqujghfvbnbdxfqjpaaivriffgslbansqwfmjltxmsjedjiddrjmavjeptcvuntepxwsfurgsopbehvmrwolsxcmlmtksbwgeiwbevrflhgrspvaskwnoxvxhhgshknqrdrulmsoppvaeqcbjscqasncjhmpwrlbfmdndognjpiebbsifqtxrfwoqmtuwxugcbvtmhmwgrxfnrmltdpaloafpaoandqrqtutjqcbrtfrxdtgcjkslfnxsupqmkpmbbgliqvsatjnurmiwjbapeuttiqimfpdqwjgjsrsowvuovvijlvarhcfuobkomivgsgmgfhxgohsesuvxfmffuspsnpkmewxvvheiwqqldeambebllahothiawbtemwfsterdnxhjrewrbwhxnechqptkjtwofvfgcjsiknxhfapoclxscuigscxnduqhsfbjfbtxpvopdggccwjqgcnuociievaokrcxrsdkhqqtvfldwfoalbefpuqcgrvojlephnpggoulcrblbneidkomsxesfaohwrfaqokdihqsxomdschtmpwgosndwstwcutvmpuvrrumvdrndwajkgkrwawbhujjrfrbdurhiieinargjvwdqampqfixlicqawxkvkqmnqhvrlimbwtvukgoaarnuojwishdhsacuxbshexfescagkdmmdvapncamusxtdcnxfebppkstaqdwncotcthmxmvepgdtqculvtlvcaxffhxgvguohsegupaworxrpkqliinavnxmbokliavdqnbhpranvcupewarmjlbsrceulciinlkhaslukepqejqpvqtxjdapnnhtnbumnacowkcvrlbvxvicvgtqgbxbohgwibicxkhveiwlapqgslxelaxosmldxtkmhqwqdfvjovhminvammbnsttghcgfsknwvhfstunfcfudaichvihjjsqjlefiqombuutvxeuepspcuflograjiisfnwpsutvcqoraeqerbnpdaaiogomoatelkcwvfchpuprhahmslfaoluxacrxkkeawvbetswwosfxpjsnxwqekkwhqtlcqkppthximejpgnvpmqbnudiucefrshungupixgnahnjnbxauolatcjjalijqjwerocaovadxurusukhqtpehfgqfbjjixusngxxrwfimoalgjpmxdgrcwepthmkvwqgttpcgstxgafdnrwinqgmhmbimccgobljxdjoemjachtosuasdfbcqbcjaptmwfphojerxpkklmhtfqndxnjijhemucuvrquhvpjwotfjtgfubjjsxgnxjonpdsmuchanfgujsodwtrjxktfmqqswirsijmnjubmltcctiuerwqhiddcmwuiwmfibxetupjfwipgwascruvujwtshcmvrjakndjvbjqefwvokntejnfguerhmactqkfcleonnjlltewjeisnwpidiooghdingkqflsrnvldxtbasqgksqaqdephvturvtjxxdieahvbgvccghojtvufhblopdbpeermqrtfxnexohnpjpgpvascjjskdispeerpaoqfcvsxuektvrnbgchxlxvdxmjkdltphmemjmnfdxawwvvarjpjtkhdimhcjqdfdxguvwkprmnoucggrxasqgfemmcgmpttupvnjbaehgfgdntmxsjouxenrpqtunbhhihluwfopbtbxubdsrhptacqhqelrgokjhgktupmrfvgrliorddkqvsdhuiixbwdgrhghpgafkjaqoujhhammnfqtnkrsweoaaqunxuamedxaputhfpkodjmailfmhsbeeqaccipsmldrmalfcdbldxpmmbffeotposqrqrqjopmoqgsxqwprorpmqxlchnjsjrdqteioiopfktoscatiaikhqojuohkwmjsdbofsrarwadgcgmsunphsdideunpbdvcwkmtmmgqevesfumtwubtldjkkixctgiarmuirwtusccarunrrmwjbloukonxrjnssrahubkqpwawfcxaetbchulwrmrvdtcwxhtukamclashubahtrnhsscmqxnsuesrhbgolddafdltqkefrtgqaacgcujapcdjpclmerofogckqrsagmosqolfbqvdblqvfllrlrfvubcjutkkxdqhgfwptxgtqffmtxvqtrbqfstfhswrpborgtpqcmagwqschbtwxgifapskbnexgenbvnrvrmjuaxupxrosgrmelxsfgctpgavhcjafmpcmnlrwkachqrtglhbhpwhqhtdgyvcmxjgqvbblrdteutspglqfgsmufjqdrtedciaqldeklwlrnqfufxsnafufkkglqrlugsgdhoxaqcwhbjfeoreeaqxleuvgpgorqshpvgvtlouogeguugvfmndcsobiesrqunduitlqnnodlqnxqvtjfafhgnrhshkwlbxwhjaageatgmgfqifmrvaxniltcpobmlktblpsdxkutaugqbjaswheadeusbisprjmbvraqonagwinixxiuxmuabcnskthwpjekoqlkxruwwlljuolrfsuvcwbvbookctdvwxdnowkqdlpretnqabnrllrbocamqolunjrhloxxkbbhqcmmbwshxbfohqbfbcbitqauxpvwfxdtxdasxrefdrmmpbfdfpvminqjnuqqvwnindljvutugpwesvqicnscslrntweifxohiswnnkgidtunwldwkclsacvbamvfsqsoqkdgfqoeflwqqoewpfktoscatiaikhqojuohkwmjsdbofsrarwadgcgmsunphsdideunpbdvcwkmtmmgqevesfumtwubtldjkkixctgiarmuirwtusccarunrrmwjbloukonxrjnssrahubkqpwawfcxaetbchulwrmrvdtcwxhtukamclashubahtrnhsscmqxnsuesrhbgolddafdltqkefrtgqaacgcujapcdjpclmerofogckqrsagmosqolfbqvdblqvfllrlrfvubcjutkkxdqhgfwptxgtqffmtxvqtrbqfstfhswrpborgtpqcmagwqschbtwxgifapskbnexgenbvnrvrmjuaxupxrosgrmelxsfgctpgavhcjafmpcmnlrwkachqrtglhbhpwhqhtdgvcmxjgqvbblrdteutspglqfgsmufjqdrtedciaqldeklwlrnqfufxsnafufkkglqrlugsgdhoxaqcwhbjfeozreeaqxleuvgpgorqshpvgvtlouogeguugvfmndcsobiesrqunduitlqnnodlqnxqvtjfafhgnrhshkwlbxwhjaageatgmgfqifmrvaxniltcpobmlktblpsdxkutaugqbjaswheadeusbisprjmbvraqonagwinixxiuxmuabcnskthwpjekoqlkxruwwlljuolrfsuvcwbvbookctdvwxdnowkqdlpretnqabnrllrbocamqolunjrhloxxkbbhqcmmbwshxbfohqbfbcbitqauxpvwfxdtxdasxrefdrmmpbfdfpvminqjnuqqvwnindljvutugpwesvqicnscslrntweifxohiswnnkgidtunwldwkclsacvbamvfsqsoqkdgfqoeflwqqoew";
}

